apiVersion: apps/v1
kind: Deployment
metadata:
 name: project-mpi
 labels:
   app: project-mpi
spec:
 replicas: 4
 selector:
   matchLabels:
     app: project-mpi
 template:
   metadata:
     labels:
       app: project-mpi
   spec:
     containers:
     - name: project-mpi
       image: gcr.io/google-cloud-project-id/project-mpi
       ports:
       - containerPort: 22
